In [1]:
from sklearn.datasets import fetch_20newsgroups
from keras.preprocessing.text import Tokenizer

import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.


In [2]:
cats = ['alt.atheism', 'sci.space']
data = fetch_20newsgroups(subset='train', categories=cats)

In [3]:
data["data"][0]

'From: bil@okcforum.osrhe.edu (Bill Conner)\nSubject: Re: Not the Omni!\nNntp-Posting-Host: okcforum.osrhe.edu\nOrganization: Okcforum Unix Users Group\nX-Newsreader: TIN [version 1.1 PL6]\nLines: 18\n\nCharley Wingate (mangoe@cs.umd.edu) wrote:\n: \n: >> Please enlighten me.  How is omnipotence contradictory?\n: \n: >By definition, all that can occur in the universe is governed by the rules\n: >of nature. Thus god cannot break them. Anything that god does must be allowed\n: >in the rules somewhere. Therefore, omnipotence CANNOT exist! It contradicts\n: >the rules of nature.\n: \n: Obviously, an omnipotent god can change the rules.\n\nWhen you say, "By definition", what exactly is being defined;\ncertainly not omnipotence. You seem to be saying that the "rules of\nnature" are pre-existant somehow, that they not only define nature but\nactually cause it. If that\'s what you mean I\'d like to hear your\nfurther thoughts on the question.\n\nBill\n'

[The quick brown fox jumped over the lazy dog](https://ru.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog)

In [9]:
from keras.preprocessing.text import text_to_word_sequence

text = 'The quick brown fox jumped over the lazy dog'
result = text_to_word_sequence(text)

result

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']

In [15]:
from keras.preprocessing.text import one_hot

words = set(text_to_word_sequence(text))
vocab_size = len(words)

result = one_hot(text, round(vocab_size*1.3))

print(vocab_size)
print(result)

8
[1, 5, 2, 8, 1, 2, 1, 3, 9]


In [6]:
words

{'brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the'}

In [17]:
from keras.preprocessing.text import hashing_trick

words = set(text_to_word_sequence(text))
vocab_size = len(words)
result = hashing_trick(text, round(vocab_size*10), hash_function='md5')

print(vocab_size)
print(result)

8
[38, 78, 61, 55, 16, 71, 38, 8, 10]


In [18]:
from keras.preprocessing.text import Tokenizer
docs = ['Well done!', 'Good work', 'Great effort', 'nice work', 'Excellent!']
t = Tokenizer()
t.fit_on_texts(docs)

#word_counts: A dictionary of words and their counts.
print(t.word_counts)

#word_docs: A dictionary of words and how many documents each appeared in.
print(t.document_count)

#word_index: A dictionary of words and their uniquely assigned integers.
print(t.word_index)

#document_count:An integer count of the total number of documents that were used to fit the Tokenizer.
print(t.word_docs)

OrderedDict([('well', 1), ('done', 1), ('good', 1), ('work', 2), ('great', 1), ('effort', 1), ('nice', 1), ('excellent', 1)])
5
{'work': 1, 'well': 2, 'done': 3, 'good': 4, 'great': 5, 'effort': 6, 'nice': 7, 'excellent': 8}
defaultdict(<class 'int'>, {'well': 1, 'done': 1, 'good': 1, 'work': 2, 'great': 1, 'effort': 1, 'nice': 1, 'excellent': 1})


In [19]:
encoded_docs = t.texts_to_matrix(docs, mode='count')
print(encoded_docs)

[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [20]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data["data"])
len(data["data"])

x = tokenizer.texts_to_matrix(data["data"], mode='binary')

In [21]:
x

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 1., 1.]])

In [22]:
set(data["target"])

{0, 1}

In [23]:
print([i for i, x in enumerate(data["target"]) if x == 1])

[1, 2, 3, 5, 6, 10, 11, 12, 13, 14, 17, 18, 20, 21, 27, 29, 31, 34, 37, 40, 42, 43, 44, 46, 47, 48, 51, 52, 54, 55, 56, 60, 62, 65, 67, 70, 71, 72, 73, 76, 77, 78, 79, 81, 82, 84, 85, 86, 88, 91, 95, 96, 97, 98, 100, 101, 104, 107, 108, 109, 119, 125, 126, 127, 128, 129, 130, 132, 133, 134, 135, 139, 141, 143, 145, 146, 149, 150, 151, 152, 153, 154, 157, 158, 159, 160, 163, 164, 165, 167, 168, 169, 170, 171, 173, 174, 175, 179, 180, 181, 185, 187, 191, 192, 193, 195, 196, 200, 202, 203, 207, 208, 209, 210, 212, 213, 216, 217, 218, 219, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 233, 234, 237, 240, 241, 242, 245, 246, 249, 250, 251, 252, 254, 256, 260, 263, 265, 268, 270, 271, 272, 274, 275, 283, 288, 289, 290, 292, 293, 296, 299, 302, 303, 306, 308, 311, 312, 313, 314, 315, 318, 319, 322, 323, 324, 325, 327, 329, 334, 335, 339, 342, 343, 345, 346, 349, 350, 356, 357, 359, 361, 364, 365, 367, 371, 372, 373, 375, 376, 377, 379, 380, 382, 383, 384, 385, 386, 390, 391, 393, 394, 395

In [24]:
print([i for i, x in enumerate(data["target"]) if x == 0])

[0, 4, 7, 8, 9, 15, 16, 19, 22, 23, 24, 25, 26, 28, 30, 32, 33, 35, 36, 38, 39, 41, 45, 49, 50, 53, 57, 58, 59, 61, 63, 64, 66, 68, 69, 74, 75, 80, 83, 87, 89, 90, 92, 93, 94, 99, 102, 103, 105, 106, 110, 111, 112, 113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 124, 131, 136, 137, 138, 140, 142, 144, 147, 148, 155, 156, 161, 162, 166, 172, 176, 177, 178, 182, 183, 184, 186, 188, 189, 190, 194, 197, 198, 199, 201, 204, 205, 206, 211, 214, 215, 220, 221, 232, 235, 236, 238, 239, 243, 244, 247, 248, 253, 255, 257, 258, 259, 261, 262, 264, 266, 267, 269, 273, 276, 277, 278, 279, 280, 281, 282, 284, 285, 286, 287, 291, 294, 295, 297, 298, 300, 301, 304, 305, 307, 309, 310, 316, 317, 320, 321, 326, 328, 330, 331, 332, 333, 336, 337, 338, 340, 341, 344, 347, 348, 351, 352, 353, 354, 355, 358, 360, 362, 363, 366, 368, 369, 370, 374, 378, 381, 387, 388, 389, 392, 398, 399, 400, 402, 403, 404, 405, 408, 409, 415, 419, 420, 422, 423, 424, 425, 427, 429, 430, 431, 432, 433, 434, 435, 437, 438, 

In [27]:
import numpy as np

In [25]:
x[504]

array([0., 1., 1., ..., 0., 0., 0.])

In [28]:
np.dot(x[504], x[542])

44.0

In [30]:
print(x[504], x[542])

[0. 1. 1. ... 0. 0. 0.] [0. 1. 1. ... 0. 0. 0.]


In [29]:
np.dot(x[540], x[543])

19.0

## GloVe Word Embeddings

In [31]:
import pickle
import numpy as np
import re
import json

In [32]:
vecs = np.load("glove_vectors_100d.npy")
vecs50 = np.load("glove_vectors_50d.npy")

In [33]:
with open('words.txt') as f:
    content = f.readlines()
words = [x.strip() for x in content]

In [34]:
wordidx = json.load(open('wordsidx.txt'))

In [35]:
len(words)

400000

In [36]:
words[:10]

['the', ',', '.', 'of', 'to', 'and', 'in', 'a', '"', "'s"]

In [37]:
type(vecs)

numpy.ndarray

In [38]:
words[11853]

'feminist'

In [ ]:
vecs[11853]

In [39]:
from scipy.spatial.distance import cosine as dist

In [40]:
dist(vecs[wordidx["puppy"]], vecs[wordidx["dog"]])

0.27636247873306274

In [41]:
dist(vecs[wordidx["avalanche"]], vecs[wordidx["antique"]])

0.9621107056736946

In [42]:
import plotly
import plotly.graph_objs as go    
from IPython.display import IFrame

In [43]:

def plotly_2d(Y, cat_labels):
    trace_dict = {}
    for i, label in enumerate(cat_labels):
        trace_dict[i] = go.Scatter(
            x=Y[i*5:(i+1)*5, 0],
            y=Y[i*5:(i+1)*5, 1],
            mode='markers',
            marker=dict(
                size=8,
                line=dict(
                    color='rgba('+ str(i*40) + ',' + str(i*40) + ',' + str(i*40) + ', 0.14)',
                    width=0.5
                ),
                opacity=0.8
            ),
            text = my_words[i*5:(i+1)*5],
            name = label
        )

    data = [item for item in trace_dict.values()]
    layout = go.Layout(
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=0
        )
    )

    plotly.offline.plot({
        "data": data,
        "layout": layout
    })

In [44]:
def plotly_3d(Y, cat_labels):
    trace_dict = {}
    for i, label in enumerate(cat_labels):
        trace_dict[i] = go.Scatter3d(
            x=Y[i*5:(i+1)*5, 0],
            y=Y[i*5:(i+1)*5, 1],
            z=Y[i*5:(i+1)*5, 2],
            mode='markers',
            marker=dict(
                size=8,
                line=dict(
                    color='rgba('+ str(i*40) + ',' + str(i*40) + ',' + str(i*40) + ', 0.14)',
                    width=0.5
                ),
                opacity=0.8
            ),
            text = my_words[i*5:(i+1)*5],
            name = label
        )

    data = [item for item in trace_dict.values()]
    layout = go.Layout(
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=0
        )
    )

    plotly.offline.plot({
        "data": data,
        "layout": layout
    })

In [45]:
categories = [
              "bugs", "music", 
              "pleasant", "unpleasant", 
              "science", "arts"
             ]

In [46]:
my_words = [
            "maggot", "flea", "tarantula", "bedbug", "mosquito", 
            "violin", "cello", "flute", "harp", "mandolin",
            "joy", "love", "peace", "pleasure", "wonderful",
            "agony", "terrible", "horrible", "nasty", "failure", 
            "physics", "chemistry", "science", "technology", "engineering",
            "poetry", "art", "literature", "dance", "symphony",
           ]


In [47]:
X = np.array([wordidx[word] for word in my_words])

In [48]:
vecs[X].shape

(30, 100)

In [49]:
embeddings = np.concatenate((vecs[X], vecs[:10000,:]), axis=0); embeddings.shape

(10030, 100)

In [50]:
from sklearn import decomposition

In [51]:
pca = decomposition.PCA(n_components=3).fit(embeddings.T)
components = pca.components_
plotly_3d(components.T[:len(my_words),:], categories)
IFrame('temp-plot.html', width=600, height=400)

In [52]:
from sklearn.neighbors import NearestNeighbors

In [53]:
neigh = NearestNeighbors(n_neighbors=10, radius=0.5, metric='cosine', algorithm='brute')
neigh.fit(vecs)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=10, p=2, radius=0.5)

In [54]:
distances, indices = neigh.kneighbors([vecs[wordidx["intelligence"]]])

In [55]:
[(words[int(ind)], dist) for ind, dist in zip(list(indices[0]), list(distances[0]))]

[('intelligence', 1.1920929e-07),
 ('cia', 0.25781953),
 ('information', 0.27898037),
 ('security', 0.30368996),
 ('fbi', 0.30377108),
 ('military', 0.3065179),
 ('secret', 0.3106637),
 ('counterterrorism', 0.3237375),
 ('pentagon', 0.33488154),
 ('defense', 0.34354317)]

In [56]:
new_vec = vecs[wordidx["artificial"]] + vecs[wordidx["intelligence"]]

In [57]:

new_vec

array([ 3.44600081e-02, -1.18469983e-01,  7.46029019e-01,  3.25609982e-01,
        3.25583994e-01, -1.46993995e+00, -8.71460021e-01, -9.42110002e-01,
        6.79129958e-02,  9.22033012e-01,  6.81050003e-01, -3.72929007e-01,
        1.09686995e+00,  7.19560027e-01,  1.35152149e+00,  1.24931002e+00,
        6.62050009e-01,  1.90050006e-01, -2.70690024e-01, -4.43699956e-02,
       -1.23197997e+00,  1.74419999e-01,  7.57689953e-01, -9.17719960e-01,
       -1.21841693e+00,  6.95879042e-01, -1.96550012e-01, -4.15010005e-01,
       -3.35797995e-01,  5.45199990e-01,  5.88955045e-01, -2.98979990e-02,
       -9.74384010e-01, -8.93670022e-01,  2.28260010e-01, -2.09187999e-01,
       -1.37952995e+00,  1.78108001e+00,  2.26889998e-01,  4.69969988e-01,
       -3.04547012e-01, -1.57320023e-01, -4.78008002e-01,  3.07079971e-01,
        4.20230001e-01, -4.43358004e-01,  1.60180002e-01,  1.44280016e-01,
       -9.52759981e-01, -5.56486011e-01,  7.53669977e-01,  1.82048991e-01,
        1.40083003e+00,  

In [58]:
distances, indices = neigh.kneighbors([new_vec])

In [59]:
[(words[int(ind)], dist) for ind, dist in zip(list(indices[0]), list(distances[0]))]

[('intelligence', 0.1883161),
 ('artificial', 0.25617576),
 ('information', 0.3256532),
 ('knowledge', 0.33641893),
 ('secret', 0.36480355),
 ('human', 0.36726683),
 ('biological', 0.37090683),
 ('using', 0.37736303),
 ('scientific', 0.38513905),
 ('communication', 0.38691515)]

In [60]:
new_vec = vecs[wordidx["doctor"]] - vecs[wordidx["he"]] + vecs[wordidx["she"]]
distances, indices = neigh.kneighbors([new_vec])
[(words[int(ind)], dist) for ind, dist in zip(list(indices[0]), list(distances[0]))]

[('doctor', 0.13456279),
 ('nurse', 0.22582489),
 ('mother', 0.27610385),
 ('woman', 0.29901665),
 ('pregnant', 0.32096934),
 ('girl', 0.3324105),
 ('patient', 0.34357917),
 ('she', 0.35723114),
 ('child', 0.3631252),
 ('herself', 0.36338794)]

In [ ]:
new_vec = vecs[wordidx["doctor"]] - vecs[wordidx["she"]] + vecs[wordidx["he"]]
distances, indices = neigh.kneighbors([new_vec])
[(words[int(ind)], dist) for ind, dist in zip(list(indices[0]), list(distances[0]))]

In [ ]:
from keras.datasets import imdb
from keras.utils.data_utils import get_file
idx = imdb.get_word_index()

In [ ]:
import keras.backend as K

def limit_mem():
    K.get_session().close()
    cfg = K.tf.ConfigProto()
    cfg.gpu_options.allow_growth = True
    cfg.gpu_options.per_process_gpu_memory_fraction = 0.6
    K.set_session(K.tf.Session(config=cfg))
    
limit_mem()

In [ ]:
idx_arr = sorted(idx, key=idx.get)
idx_arr[:10]

In [ ]:
idx2word = {v: k for k, v in idx.items()}

In [ ]:
path = get_file('imdb_full.pkl',
                origin='https://s3.amazonaws.com/text-datasets/imdb_full.pkl',
                md5_hash='d091312047c43cf9e4e38fef92437263')
f = open(path, 'rb')
(x_train, labels_train), (x_test, labels_test) = pickle.load(f)

In [ ]:
len(x_train)

In [ ]:

', '.join(map(str, x_train[0]))

In [ ]:
idx2word[23022]

In [ ]:
' '.join([idx2word[o] for o in x_train[0]])

In [ ]:
labels_train[:10]

In [ ]:
vocab_size = 5000

trn = [np.array([i if i<vocab_size-1 else vocab_size-1 for i in s]) for s in x_train]
test = [np.array([i if i<vocab_size-1 else vocab_size-1 for i in s]) for s in x_test]

In [ ]:
lens = np.array([len(review) for review in trn])
(lens.max(), lens.min(), lens.mean())

In [ ]:
from keras.preprocessing import sequence
seq_len = 500

trn = sequence.pad_sequences(trn, maxlen=seq_len, value=0)
test = sequence.pad_sequences(test, maxlen=seq_len, value=0)
trn.shape

In [ ]:
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from keras.layers.core import Flatten, Dense, Dropout
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.optimizers import Adam

In [ ]:
conv1 = Sequential([
    Embedding(vocab_size, 50, input_length=seq_len, dropout=0.4),
    Convolution1D(64, 5, border_mode='same', activation='relu'),
    Dropout(0.2),
    MaxPooling1D(),
    Flatten(),
    Dense(100, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')])

conv1.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])
conv1.fit(trn, labels_train, validation_data=(test, labels_test), nb_epoch=4, batch_size=64)

In [ ]:
conv1.optimizer.lr=1e-4
conv1.fit(trn, labels_train, validation_data=(test, labels_test), nb_epoch=4, batch_size=64)

In [ ]:
def create_emb():
    n_fact = vecs50.shape[1]
    emb = np.zeros((vocab_size, n_fact))

    for i in range(1,len(emb)):
        word = idx2word[i]
        if word and re.match(r"^[a-zA-Z0-9\-]*$", word):
            src_idx = wordidx[word]
            emb[i] = vecs50[src_idx]
        else:
            # If we can't find the word in glove, randomly initialize
            emb[i] = np.random.normal(scale=0.6, size=(n_fact,))

    # This is our "rare word" id - we want to randomly initialize
    emb[-1] = np.random.normal(scale=0.6, size=(n_fact,))
    emb/=3
    return emb

In [ ]:
emb = create_emb()
model = Sequential([
    Embedding(vocab_size, 50, input_length=seq_len, dropout=0.4, weights=[emb]),
    Convolution1D(64, 5, border_mode='same', activation='relu'),
    Dropout(0.2),
    MaxPooling1D(),
    Flatten(),
    Dense(100, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')])
model.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])
model.fit(trn, labels_train, validation_data=(test, labels_test), nb_epoch=4, batch_size=64)

In [ ]:
model.optimizer.lr=1e-4
model.fit(trn, labels_train, validation_data=(test, labels_test), nb_epoch=4, batch_size=64)